# Users-Get All Users

https://localhost:5001/api/administration
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTY2MzYxMDExNSwiZXhwIjoxNjYzOTcwMTE1LCJpYXQiOjE2NjM2MTAxMTUsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAyIn0.2xPZwtcEkikwUlU7Yj91B_038DMhPTFnkkiOpqjDhkY
